### ISSUE TITLE
Need to check if local module references ($ or #) fail to match a pid. 

### ISSUE THREAD

**Issue by tjgionet** [IntrospectiveSystems/xGraph#49]

**Comment by valyrie97** [comment]
does this not already throw an error in genesis?

**Comment by tjgionet** [comment]
Nope

**Comment by valyrie97** [comment]
whats the current behaviour?

**Comment by tjgionet** [comment]
Path must be a string received undefined, in cache interface. Happens during send -> getEntityContext -> cacheInterface.

**Comment by valyrie97** [comment]
goooootcha, so its basically just not saying anything in genesis when it fails to get the symbol, and leaves the $Reference

Should probably also add in checking for a valid pid on send, while we're at it.

**Comment by valyrie97** [comment]
[Genesis Line 1134](https://github.com/IntrospectiveSystems/xGraph/blob/release/src/Genesis.js#L1134) appears to already do this check?
