### ISSUE TITLE
Update documentation to use URI notation instead of a source object

### ISSUE THREAD

**Issue by Ahathaway97** [IntrospectiveSystems/xGraph#64]
Found from setup in the "Build a Test System" documentation

Change
```
"Core": {
    "Host": "modulebroker.xgraphdev.com"
}
```

to

```
"Core": "mb://modulebroker.xgraphdev.com"
```

**Comment by valyrie97** [comment]
@Ahathaway97 Is this just the website or does this apply to the examples as well, do they need updating?

**Comment by valyrie97** [comment]
moved to xgraph wiki
